### ISSUE TITLE
Please, help to decide how to integrate Nix Base32

### ISSUE THREAD

**Issue by Anton-Latukha** [emilypi/Base32#12]
I've seen that your code of functions accounts for the possibility of nonstandard encodings.

https://github.com/emilypi/Base32/blob/b02886217a16a7118f1e899a0ba71897fe5f91a5/src/Data/ByteString/Base32/Hex.hs#L67-L68

--- 
For simplicity during creation, Nix implemented & fixated on a custom Base32 encoding for store paths:

Dictionary is:
```haskell
--- omitted: E O U T
digits32 :: Vector Char
digits32 = Vector.fromList "0123456789abcdfghijklmnpqrsvwxyz"
```

That received a security theater (from my evaluation) reasoning explanations, like : 'because Nix relies on hashing/base encoding so much - the "special" base encoding is additional protection mechanism "preventing rainbow attacks" & nix/store offsets from the hashes used on the Internet".

---

Currently, I (need because of the Haskell code&its deps reasons) rewriting the `hnix-store` hashing/base encoding subsystem. & splitting the tasks into smaller subtasks. & going to migrate `HNix` to your `Base{16,32,64}` packages.

There are several ways:
1. The most simple & pleasant to me: consider the Nix Base32 fossilized bug enough of a widespread use phenomenon to include its dictionary into `Base32` & expose `{encode,decode}NixBase32` functions. On that decision, I would work on it & provide it according to pull requests.
2. Custom dictionary functionality is not exposed in the package (`encodeBase32_` is not provided in the package interface). In that case, those customizable encode/decode/verify should be provided for me to continue, to be able to integrate with `Base{16,32,64}` elegantly. Overall it can be a good idea to provide `./Internal` as a lower-level code package for Haskellers to be able to implement base encodings on. & so in this case I provide a separate package for NixBase32 encoding.

**Comment by emilypi** [comment]
Hi @Anton-Latukha - thanks for the issue, and it's fantastic to hear people moving on the `baseN` packages!

- With respect to the first issue of supporting Nix, I'm happy to add support for it in this library, in the same way I'm happy to support Crockford and Z alphabets (as seen in #2). The only thing holding them back is my own amount of free time, but I'm happy to review and merge PR's if someone gets to them before I do. Nix is certainly pervasive enough for me to consider adding full support directly in `base32`. If you'd like to do the PR, then only three things are needed: 
   1. An encoding alphabet and decoding lookup table pair. The latter you can see examples of in `Data.Base32.ByteString.Internal.Tables`. 
   2. Support for Textual values, which is mostly copypasta. 
   3. Support for Nix alphabets in the test harnesses, along with test vectors that stress the entirety of the alphabet. 
   
  I will probably have time sometime mid-week to get to this otherwise. 

- With respect to exposing internals, that's an interesting idea. I'm certainly happy to start exposing that API, as long as we throw the caveat on top of it that it may change significantly from time to time as my skills improve and the GHC api evolves. I'd welcome PR's for both. To my knowledge, the only things we'd need to export from that module in addition to what's already there are what's in `Data.Base32.ByteString.Internal.Head`. My only worry is that this knocks alignment out of balance. It's something to monitor and benchmark carefully. 

I can have the latter done relatively quickly assuming benchmarks play nicely.

**Comment by Anton-Latukha** [comment]
Ok, lets move go with the second option, opened  [report](https://github.com/emilypi/Base32/issues/13) for it.
& if after a time the need arrives & we are not there I would go with the first option.

**Comment by emilypi** [comment]
Sounds good to me!

**Comment by emilypi** [comment]
Okay @Anton-Latukha - [base32-0.2.1.0](https://hackage.haskell.org/package/base32) is officially out, exposing the internal module with the main drivers to the encode and decode functionality, as well as the padding and validity checks and their associated documentation. I'll get to working on splitting this functionality out in `0.3`, which should take a month or two, time permitting. In the meantime, i'm closing this issue so we can focus on #13

**Comment by rickynils** [comment]
@emilypi I tried using the exposed internal `decodeBase32_` function to implement Nix Base32 decoding this way:

```
base32DecodeBS :: ByteString -> IO (Either Text ByteString)
base32DecodeBS = decodeBase32_ lookupBase32CharsPtr

{- NOINLINE lookupBase32CharsPtr -}
lookupBase32CharsPtr :: Ptr Word8
lookupBase32CharsPtr =
  unsafePerformIO $! unsafeUseAsCString lookupBase32Chars (pure . castPtr)

lookupBase32Chars :: ByteString
lookupBase32Chars = "\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\0\1\2\3\4\5\6\7\8\9\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\10\11\12\13\255\14\15\16\17\18\19\20\21\22\255\23\24\25\26\255\255\27\28\29\30\31\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255"
```

I made the following observations:

* Some Nix hashes are not decodable (returns errors like `Left "invalid character at offset: 52"`). It could be related to hash lenghts but I haven't looked closer.
* The hashes that are successfully decoded are **reversed** compared to the Nix implementation. So, running `ByteString.reverse` on the result produces the correct output.
* The `decodeBase32_` function is about twice as fast as my own Nix Base32 decoder which is a pretty straightforward translation of the Nix CPP implementation, backed by `Data.Vector.Unboxed.Mutable`. I'm mostly interested in encoding/decoding small data (< 100 bytes), the difference could be bigger for larger data sets.
